crowdanki_uuid: eb203d7c-1325-11ec-813b-acde48001122
dyn: 0
extendNew: 0
extendRev: 0
name: Japanese
desc: 'My personal collection of Japanese flash cards.'
deck_configurations:
- __type__: DeckConfig
  autoplay: true
  crowdanki_uuid: eb2051ea-1325-11ec-813b-acde48001122
  dyn: false
  interdayLearningMix: 0
  lapse:
    delays:
    - 10.0
    leechAction: 1
    leechFails: 6
    minInt: 1
    mult: 0.5
  maxTaken: 60
  name: Japanese Study
  new:
    bury: false
    delays:
    - 1.0
    - 10.0
    - 60.0
    initialFactor: 1310
    ints:
    - 1
    - 2
    - 0
    order: 1
    perDay: 10
  newGatherPriority: 0
  newMix: 0
  newPerDayMinimum: 0
  newSortOrder: 0
  replayq: false
  rev:
    bury: false
    ease4: 1.3
    hardFactor: 1.2
    ivlFct: 1.91
    maxIvl: 36500
    perDay: 200
  reviewOrder: 0
  timer: 0
deck_config_uuid: eb2051ea-1325-11ec-813b-acde48001122
